# Generated by Django 4.2.5 on 2023-11-20 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('dateEntry', models.DateTimeField(auto_now_add=True)),
                ('overall', models.IntegerField()),
                ('deliverables', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('ratingOn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingOn', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
